lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TasktrackerWeb.Sessionplug
    plug TasktrackerWeb.Dropdownplug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    post "/updateTaskTime", TaskController, :updateTime
    post "/addReportees", ReporteeController, :addReportees
    get "/myResources", ReporteeController, :get_reportees
    get "/taskReport", TaskController, :generateTaskReport
    resources "/users", UserController
    resources "/tasks", TaskController
    resources "/reportees", ReporteeController
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete


  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TasktrackerWeb do
     pipe_through :api
       resources "/timeblocks", TimeblockController, except: [:new, :edit]
   end
end

lib/tasktracker_web/templates/page/dashboard.html.eex
<div class="jumbotron">
  <center>
<h1> <%= @current_user.name %>'s Dashboard <h1></center>
  <div class="row">
    <div class="col-sm-6">
      <p class="lead">
      <strong> Total tasks in the system </strong>
         <%= @tasks %> <br />
          <strong> Total number of users in the system </strong>
           <%= @users %><br />
        <strong> Tasks pending your action </strong>
             <%= @assigned %>
          </p>
  </div>

  <div class="col-sm-6">
    <span><%= link "My Profile", to: "/users/#{@current_user.id}", class: "btn btn-default" %></span>
    <span><%= link "View Tasks", to: task_path(@conn, :index), class: "btn btn-default" %></span>
    <%= if Tasktracker.Accounts.is_manager(@current_user.id) do %>
    <span><%= link "View Task Report", to: task_path(@conn, :generateTaskReport), class: "btn btn-default" %></span>
    <span><%= link "Open New Task", to: task_path(@conn, :new), class: "btn btn-default" %></span>
    <% end %>
  </div>

</div>

lib/tasktracker_web/templates/page/index.html.eex
<h1>Log In</h1>
   <!-- session_path(@conn, :create) -->
   <%= form_tag("/session", method: :post) do %>
     <div class="form-group">
       Email
       <input type="email" name="email" placeholder="user@example.com" >
     </div>
     <!-- passwords come later -->
     <div class="form-group">
       <button class="btn btn-primary">Log in</button>
       <%= link "Register", to: user_path(@conn, :new) %>
     </div>
   <% end %>