lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TasktrackerWeb.Sessionplug
    plug TasktrackerWeb.Dropdownplug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/dashboard", PageController, :dashboard
    post "/updateTaskTime", TaskController, :updateTime
    post "/addReportees", ReporteeController, :addReportees
    get "/myResources", ReporteeController, :get_reportees
    get "/taskReport", TaskController, :generateTaskReport
    resources "/users", UserController
    resources "/tasks", TaskController
    resources "/reportees", ReporteeController
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete


  end

  # Other scopes may use custom stacks.
  scope "/api/v1", TasktrackerWeb do
     pipe_through :api
       resources "/timeblocks", TimeblockController, except: [:new, :edit]
   end
end

lib/tasktracker/task_handler/task.ex
defmodule Tasktracker.TaskHandler.Task do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.TaskHandler.Task


  schema "tasks" do
    field :title, :string
    field :body, :string
    field :status, :boolean, default: false
    belongs_to :creator, Tasktracker.Accounts.User, foreign_key: :createdBy_id
    belongs_to :assigner, Tasktracker.Accounts.User, foreign_key: :assignedTo_id
    timestamps()
  end

  @doc false
  def changeset(%Task{} = task, attrs) do
    task
    |> cast(attrs, [:title,:body, :status, :createdBy_id, :assignedTo_id])
    |> validate_required([:title, :body, :status, :createdBy_id])

  end

end

lib/tasktracker_web/controllers/task_controller.ex
defmodule TasktrackerWeb.TaskController do
  use TasktrackerWeb, :controller


  alias Tasktracker.TaskHandler
  alias Tasktracker.TaskHandler.Task


  def index(conn, _params) do
    user_id = get_session(conn, :user_id)
    if(user_id) do
    user = Tasktracker.Accounts.get_user(user_id || -1)
    IO.puts("user is #{user.id}")
    taskPerId = TaskHandler.created_by(user.id)
    assigned_task = TaskHandler.assigned_tasks(user.id)
    timeblockdata=TaskHandler.gettimeMap(user.id)
    IO.puts("time block map is")
    IO.inspect(timeblockdata)
    task_time_info = Enum.map(timeblockdata, fn(x) -> TaskHandler.eachTaskEndTime(x) end)
    task_time_info = List.flatten(task_time_info)
    task_time_info = Enum.reduce(task_time_info, %{}, fn(x, values) ->
    Map.put(values, x["task_id"], x["id"])
    end)
    IO.inspect(task_time_info)
    tasks = TaskHandler.list_tasks()
    render(conn, "index.html", tasks: tasks, taskPerId: taskPerId, tasktime: task_time_info)
  else
    conn
    |> put_flash(:error, "Cannot view Tasks, Please login first")
    |> redirect(to: page_path(conn, :index))
  end
  end

  def new(conn, _params) do
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    if(user) do
    manager_check  = Tasktracker.Accounts.is_manager(user_id)
    if(manager_check == true) do
    changeset = TaskHandler.change_task(%Task{})
    render(conn, "new.html", changeset: changeset)
  else
    conn
    |> put_flash(:error, "Cannot create tasks, permission denied")
    |> redirect(to: page_path(conn, :index))
  end
  else
    conn
    |> put_flash(:error, "Cannot create Tasks, Please login first")
    |> redirect(to: page_path(conn, :index))
  end
  end

  def create(conn, %{"task" => task_params}) do
    user_id = get_session(conn, :user_id)
    TaskTr
    if(user_id) do
      assigners = TaskHandler.getSelectData()
      IO.puts("task parameters are ")
      {assignedTo_id, ""} = Integer.parse(task_params["assignedTo_id"])
      assigned_user_manager = Tasktracker.Reports.get_user_manager(assignedTo_id)
      if(assigned_user_manager) do
        if(assigned_user_manager == user_id) do
          case TaskHandler.create_task(task_params) do
            {:ok, task} ->
              conn
              |> put_flash(:info, "Task created successfully.")
              |> redirect(to: task_path(conn, :show, task))
            {:error, %Ecto.Changeset{} = changeset} ->
              IO.inspect(changeset)
              render(conn, "new.html", changeset: changeset)
          end
        else
          conn
          |> put_flash(:error, "You are not the manager of this user, only managers can assign tasks")
          |> redirect(to: page_path(conn, :index))
        end
      else
        conn
        |> put_flash(:error, "Cannot assign tasks to a user without manager")
        |> redirect(to: page_path(conn, :index))
      end
    else
      conn
      |> put_flash(:error, "Cannot create Tasks, Please login first")
      |> redirect(to: page_path(conn, :index))
end
  end

  def show(conn, %{"id" => id}) do
    user_id = get_session(conn, :user_id)
    timeblocks = TaskHandler.getTaskTimeblocks(id)
    IO.inspect(timeblocks)
    if(user_id) do
    task = TaskHandler.get_task(id)
    if(task) do
      render(conn, "show.html", task: task, timeblocks: timeblocks)
    else
      conn
      |> put_flash(:error, "Task does not exist")
      |> redirect(to: task_path(conn, :index))
    end

  else
    conn
    |> put_flash(:error, "Cannot view a task, Please login first")
    |> redirect(to: page_path(conn, :index))
  end
  end


  def edit(conn, %{"id" => id}) do
    task = TaskHandler.get_task!(id)
    changeset = TaskHandler.change_task(task)
    render(conn, "edit.html", task: task, changeset: changeset)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    task = TaskHandler.get_task!(id)
    IO.puts("task is")
    IO.inspect(task_params)
    if(task_params["status"] == "true" && task_params["time_taken"] == "0") do
      conn
      |> put_flash(:error, "Please update the time taken to complete this task")
      |> render("show.html", task: task)
    else
      case TaskHandler.update_task(task, task_params) do
        {:ok, task} ->
          conn
          |> put_flash(:info, "Task updated successfully.")
          |> redirect(to: task_path(conn, :show, task))
        {:error, %Ecto.Changeset{} = changeset} ->
          render(conn, "edit.html", task: task, changeset: changeset)
      end
    end
  end

  def delete(conn, %{"id" => id}) do
    task = TaskHandler.get_task!(id)
    {:ok, _task} = TaskHandler.delete_task(task)

    conn
    |> put_flash(:info, "Task deleted successfully.")
    |> redirect(to: task_path(conn, :index))
  end

  def updateTime(conn, %{"task_id" => task_id, "time_taken" => time_taken})
  do
    task = TaskHandler.get_task!(task_id)
    case TaskHandler.update_task(task, %{time_taken: time_taken}) do
    {:ok, task} ->
      conn
      |> put_flash(:info, "Task updated successfully.")
      |> redirect(to: task_path(conn, :show, task))
    {:error, %Ecto.Changeset{} = changeset} ->
      conn
      |> put_flash(:error, "Time can be updated only in the intervals of 15 minutes")
      |> redirect(to: task_path(conn, :show, task))
    end

  end

  def generateTaskReport(conn, _params) do
    current_user = conn.assigns[:current_user]
    if(current_user) do
    managercheck = Tasktracker.Accounts.is_manager(current_user.id)
    if (managercheck) do
    assigned_task = TaskHandler.assigned_tasks(current_user.id)
    IO.inspect(assigned_task)
    render(conn, "taskReport.html", assigned_task: assigned_task)
  else
    conn
    |>put_flash(:error, "permission denied")
    |>redirect(to: page_path(conn, :index))
  end
  else
    conn
    |> put_flash(:error, "Cannot view Tasks, Please login first")
    |> redirect(to: page_path(conn, :index))
  end
  end

end

lib/tasktracker_web/views/task_view.ex
defmodule TasktrackerWeb.TaskView do
  use TasktrackerWeb, :view
end

lib/tasktracker_web/templates/task/edit.html.eex
<h2>Edit Task</h2>

<%= render "form2.html", Map.put(assigns, :action, task_path(@conn, :update, @task)) %>

<span><%= link "Back", to: task_path(@conn, :index) %></span>

lib/tasktracker_web/templates/task/form.html.eex
<%= form_for @changeset,  @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= label f, :status, class: "control-label" %>
    <%= checkbox f, :status, class: "checkbox" %>
    <%= error_tag f, :status %>
  </div>
  <div class="form-group">
    <%= label f, "created by: " <> String.capitalize(@current_user.name) , class: "control-label" %>
    <%= hidden_input f, :createdBy_id, value: @current_user.id, class: "form-control" %>
    <%= error_tag f, :createdBy_id %>
  </div>

  <div class="form-group">

    <%= label f, "Assigned to", class: "control-label" %>
    <%= select f, :assignedTo_id, @assigners, class: "form-control" %>
    <%= error_tag f, :assignedTo_id%>
  </div>
  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/task/form2.html.eex
<%= form_for @changeset,  @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :body, class: "control-label" %>
    <%= textarea f, :body, class: "form-control" %>
    <%= error_tag f, :body %>
  </div>

  <div class="form-group">
    <%= label f, :status, class: "control-label" %>
    <%= checkbox f, :status, class: "checkbox" %>
    <%= error_tag f, :status %>
  </div>
  <div class="form-group">
    <%= label f, :createdBy_id , class: "control-label" %>
    <%= text_input f,:createdBy_id, value: @task.creator.name, class: "form-control", disabled: true %>
    <%= error_tag f, :createdBy_id %>
  </div>

  <div class="form-group">

    <%= label f, "Assigned to", class: "control-label" %>
    <%= select f, :assignedTo_id, @assigners, class: "form-control" %>
    <%= error_tag f, :assignedTo_id%>
  </div>
  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/task/index.html.eex
<script >
 window.timeBlockPath = "<%= timeblock_path(@conn, :index) %>";
 window.csrfToken = <%=raw Poison.encode!(Plug.CSRFProtection.get_csrf_token()) %>;
</script>
<div class="row">
  <div class="col-6">
<h2> Tasks assigned to you </h2>
  </div>
 <div class="col-1 offset-5">
<span><%= link "New Task", to: task_path(@conn, :new), class: "btn btn-info" %></span>
</div>
</div>
<table class="table table-hover table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Created by </th>
      <th> Assigned To</th>
      <th>Created On </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <%= for task <- @taskPerId do %>
      <tr>
        <td><%= task.title %></td>
        <%= if(task.status) do %>
          <td>Complete</td>
          <% else %>
          <td>Not Complete</td>
        <% end %>

        <td><%= task.creator.name %></td>
          <td><%= task.assigner.name %></td>
          <td><%= task.inserted_at %> </td>
        <td class="text-right">
          <button class="start-button btn btn-primary" data-user-id="<%= @current_user.id %>" data-record-id="<%=@tasktime[task.id] %>" data-task-id = "<%= task.id%>" data-time="<%= NaiveDateTime.utc_now%>">
              Start Working
          </button>
          <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
          <%= if(Tasktracker.Accounts.is_manager(@current_user.id) == true) do %>
          <span><%= link "Edit", to: timeblock_path(@conn, :create), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
          <% end %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= if(Tasktracker.Accounts.is_manager(@current_user.id) == true) do %>
<h2>All Tasks</h2>

<table class="table table-hover table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Created by </th>
      <th> Assigned To</th>
      <th>Created On </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <%= if(task.status) do %>
        <td>Complete</td>
        <% else %>
        <td>Not Complete</td>
      <% end %>
      <td><%= task.creator.name %></td>
        <td><%= task.assigner.name %></td>
        <td><%= task.inserted_at %> </td>
      <td class="text-right">
        <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<% end %>

lib/tasktracker_web/templates/task/new.html.eex
<h2>Open New Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>

<span><%= link "Back", to: task_path(@conn, :index) %></span>

lib/tasktracker_web/templates/task/show.html.eex
<script>
window.timeBlockPath = "<%= timeblock_path(@conn, :index) %>";
</script>

<div class="card">
  <div class="card-header">
    <%= @task.title %>
  </div>
  <div class="card-body">
    <h5 class="card-title">opened by : <%= @task.creator.name %></h5>
    <p class="card-text"><%= @task.body %></p>
    <span class="btn"><%=if (@task.status == false ) do
     link "Mark as Complete", to: task_path(@conn, :edit, @task)
    else
    link "Mark as not Complete", to: task_path(@conn, :edit, @task)
    end


%></span>
<span><%= link "Update Task", to: task_path(@conn, :edit, @task), class: "btn btn-default btn-xs" %></span>
<span><%= link "Back", to: task_path(@conn, :index) %></span>
<!--<%= form_tag("/updateTaskTime", method: :post) do %>
<div class="form-group">
  <input type="number" name="time_taken" step ="15" min = "0" required/>
  <input type="hidden" name="task_id" value = <%= @task.id %>  />  </div>
 passwords come later
  <div class="form-group">
    <button class="btn btn-primary">Update Task Time</button>
  </div>
<% end %>
</div> -->
<div class="row">
  <div class="col-sm-6">
<p><h5> Add a Time block below </h5><p>
<!--<%= form_for @conn, timeblock_path(@conn, :create), [as: :timeblock], fn f->  %>

<div class="form-group">

  <%= label f, "Start Time", class: "control-label" %>
  <%= datetime_select f, :start_time, class: "form-control" %>
  <%= error_tag f, :start_time%>
</div>

<div class="form-group">
  <%= label f, "End Time", class: "control-label" %>
  <%= datetime_select f, :end_time, class: "form-control" %>
  <%= error_tag f, :end_time%>
</div>
<div class="form-group">
  <%= hidden_input f, :user_id, value: @current_user.id, class: "form-control" %>
  <%= error_tag f, :user_id %>
</div>
<div class="form-group">
  <%= hidden_input f, :task_id, value: @task.id, class: "form-control" %>
  <%= error_tag f, :task_id %>
</div>
<div class="form-group">
  <%= submit "Submit", class: "btn btn-primary" %>
</div>
<% end %>
</form> -->
<form id ="new_timeblock_form" >

 <div class="form-group">
   <label> Start Time </label>
<%= datetime_select :newTimeblock, "start_time", value: DateTime.utc_now(), class: "form-control" %> <br />
</div>

<div class="form-group">
 <label> End Time </label>
<%= datetime_select :newTimeblock, "end_time", value: DateTime.utc_now(),  class: "form-control" %><br />
</div>
<input type="hidden" id="newRecordid" value="0" /><br />
<input type="hidden" id="newTaskid" value = "<%= @task.id %>" />
<input type="hidden" id="newuserid" value = "<%= @current_user.id %>" />
<input type="button" id = "new_form_button"  value="Add" class="btn btn-primary"/>
<input type="button" id = "cancel_form_button"  value="cancel" class="btn btn-danger"/>
</form>
</div>
</div>
<div class="col-sm-6">
  <div id="form-container" style="display:none">
    <h3>Edit Timeblock Below</h3>
<form id ="edit_timeblock_form" >

 <div class="form-group">
   <label> Start Time </label>
<%= datetime_select :editTimeblock, "start_time", value: DateTime.utc_now(), class: "form-control" %> <br />
</div>

<div class="form-group">
 <label> End Time </label>
<%= datetime_select :editTimeblock, "end_time", value: DateTime.utc_now(),  class: "form-control" %><br />
</div>
<input type="hidden" id="editRecordid" value="0" /><br />
<input type="hidden" id="editTaskid" value = "<%= @task.id %>" />
<input type="hidden" id="edituserid" value = "<%= @current_user.id %>" />
<input type="button" id = "edit_form_button"  value="Update" class="btn btn-primary"/>
<input type="button" id = "cancel_form_button"  value="cancel" class="btn btn-danger"/>
</form>
</div>
</div>
</div>

<div class="timeblocks">
  <h2>Your Work History</h2>
  <table class="table table-hover table-bordered">
    <thead class="thead-light">
      <tr>
        <th>Start Time</th>
        <th>End time</th>
        <th>Time spent </th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% total = 0 %>
    <%= for time <- @timeblocks do %>
        <tr>
          <td><%= time["start_time"] %></td>
          <td><%= if(is_nil(time["end_time"])) do %> ---in progress------
          <% else %>
          <%= time["end_time"] %></td>
          <% end %>
          <%= if not is_nil(time["end_time"]) do %>
          <% variable = NaiveDateTime.diff(time["end_time"], time["start_time"]) %>
          <% else %>
          <% variable = NaiveDateTime.diff(NaiveDateTime.utc_now, time["start_time"]) %>
                    <% end %>
          <%= if (variable >=3600) do %>
            <td><%= div(variable, 3600) %> Hours</td>
            <% else %>
            <%= if(variable >= 60) do %>
              <td><%= div(variable, 60) %> Minutes </td>
              <% else %>
              <td> <%= variable %> Seconds </td>
            <% end %>

          <% end %>
          <% start_time =  time["start_time"] %>
          <% end_time = time["end_time"] %>
          <% record_id = time["id"] %>
         <td><button class="edit-btn btn btn-primary" data-record-id ="<%= record_id %>" data-start-time = "<%= start_time %> " data-end-time = "<%= end_time %>" >Edit</button>
         <span><button class="delete-timeblock-btn btn btn-danger" data-record-id="<%= record_id %>">Delete</button>
         </td>

        </tr>
    <% end %>
    </tbody>
  </table>

</div>

lib/tasktracker_web/templates/task/taskReport.html.eex
<h2>Task Report</h2>

<table class="table table-hover table-bordered">
  <thead class="thead-light">
    <tr>
      <th>Title</th>
      <th>Status</th>
      <th>Created by </th>
      <th> Assigned To</th>
      <th>Created On </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @assigned_task do %>
    <tr>
      <td><%= task.title %></td>
      <%= if(task.status) do %>
        <td>Complete</td>
        <% else %>
        <td>Not Complete</td>
      <% end %>
      <td><%= task.creator.name %></td>
        <td><%= task.assigner.name %></td>
        <td><%= task.inserted_at %> </td>
      <td class="text-right">
        <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Task", to: task_path(@conn, :new) %></span>